clc;
z = xlsread("C:\WORK\PAPERS\NEW\Abhinav Jindal\Oxford\Marginal Impact\Aggregate\Marginal Impacts_7.1.1.xlsm","Electricity Gen (HLV) 7.1.1","D4:V22");
x=0.05:0.05:0.95;
y=0.05:0.05:0.95;
surf(x,y,z);
colorbar;
xlabel('Quantiles of Health Vulnerability');
ylabel('Quantiles of Control of Corruption');
zlabel('Marginal Impact of Electricity Generation');
set(gcf,'WindowState','fullscreen');
saveas(gcf,'Electricity Generation_Health Vulnerability_Control of Corruption.png');
clc;
z = xlsread("C:\WORK\PAPERS\NEW\Abhinav Jindal\Oxford\Marginal Impact\Aggregate\Marginal Impacts_7.1.1.xlsm","Electricity Gen (HLV) 7.1.1","D28:V46");
x=0.05:0.05:0.95;
y=0.05:0.05:0.95;
surf(x,y,z);
colorbar;
xlabel('Quantiles of Health Vulnerability');
ylabel('Quantiles of Governance Effectiveness');
zlabel('Marginal Impact of Electricity Generation');
set(gcf,'WindowState','fullscreen');
saveas(gcf,'Electricity Generation_Health Vulnerability_Governance Effectiveness.png');
clc;
z = xlsread("C:\WORK\PAPERS\NEW\Abhinav Jindal\Oxford\Marginal Impact\Aggregate\Marginal Impacts_7.1.1.xlsm","Electricity Gen (HLV) 7.1.1","D52:V70");
x=0.05:0.05:0.95;
y=0.05:0.05:0.95;
surf(x,y,z);
colorbar;
xlabel('Quantiles of Health Vulnerability');
ylabel('Quantiles of Political Stability');
zlabel('Marginal Impact of Electricity Generation');
set(gcf,'WindowState','fullscreen');
saveas(gcf,'Electricity Generation_Health Vulnerability_Political Stability.png');
clc;
z = xlsread("C:\WORK\PAPERS\NEW\Abhinav Jindal\Oxford\Marginal Impact\Aggregate\Marginal Impacts_7.1.1.xlsm","Electricity Gen (HLV) 7.1.1","D76:V94");
x=0.05:0.05:0.95;
y=0.05:0.05:0.95;
surf(x,y,z);
colorbar;
xlabel('Quantiles of Health Vulnerability');
ylabel('Quantiles of Regulatory Quality');
zlabel('Marginal Impact of Electricity Generation');
set(gcf,'WindowState','fullscreen');
saveas(gcf,'Electricity Generation_Health Vulnerability_Regulatory Quality.png');
clc;
z = xlsread("C:\WORK\PAPERS\NEW\Abhinav Jindal\Oxford\Marginal Impact\Aggregate\Marginal Impacts_7.1.1.xlsm","Electricity Gen (HLV) 7.1.1","D100:V118");
x=0.05:0.05:0.95;
y=0.05:0.05:0.95;
surf(x,y,z);
colorbar;
xlabel('Quantiles of Health Vulnerability');
ylabel('Quantiles of Rule of Law');
zlabel('Marginal Impact of Electricity Generation');
set(gcf,'WindowState','fullscreen');
saveas(gcf,'Electricity Generation_Health Vulnerability_Rule of Law.png');
clc;
z = xlsread("C:\WORK\PAPERS\NEW\Abhinav Jindal\Oxford\Marginal Impact\Aggregate\Marginal Impacts_7.1.1.xlsm","Electricity Gen (HLV) 7.1.1","D124:V142");
x=0.05:0.05:0.95;
y=0.05:0.05:0.95;
surf(x,y,z);
colorbar;
xlabel('Quantiles of Health Vulnerability');
ylabel('Quantiles of Voice and Accountability');
zlabel('Marginal Impact of Electricity Generation');
set(gcf,'WindowState','fullscreen');
saveas(gcf,'Electricity Generation_Health Vulnerability_Voice and Accountability.png');
quit;
